# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import login

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#leftMenu{\n"
"   background_color : #154c79 }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(-1, -1, 231, 691))
        self.leftMenu.setStyleSheet("#leftMenu{\n"
"  background-color: #791517 }")
        self.leftMenu.setObjectName("leftMenu")
        self.label = QtWidgets.QLabel(self.leftMenu)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton.setGeometry(QtCore.QRect(10, 60, 201, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 201, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 201, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 180, 201, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 220, 201, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 260, 201, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 300, 201, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 340, 201, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 380, 201, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 420, 201, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 550, 201, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.leftMenu)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 590, 201, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.mainBody = QtWidgets.QWidget(self.centralwidget)
        self.mainBody.setGeometry(QtCore.QRect(230, -10, 911, 711))
        self.mainBody.setStyleSheet("#mainBody{\n"
"  background-color: #F5f0f0}")
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainBody)
        self.headerFrame.setObjectName("headerFrame")
        self.mainFrame = QtWidgets.QWidget(self.headerFrame)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 893, 591))
        self.mainFrame.setObjectName("mainFrame")
        self.cardFrame = QtWidgets.QWidget(self.mainFrame)
        self.cardFrame.setGeometry(QtCore.QRect(10, -20, 893, 121))
        self.cardFrame.setObjectName("cardFrame")
        self.label_2 = QtWidgets.QLabel(self.cardFrame)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.cardFrame)
        self.textBrowser.setGeometry(QtCore.QRect(130, 30, 431, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.mainFrame)
        self.label_3.setGeometry(QtCore.QRect(-280, 110, 971, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("277262295_1376424442804106_4597301472627125161_n (2).png"))
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.mainFrame)
        self.textBrowser_2.setGeometry(QtCore.QRect(450, 440, 241, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.headerFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  Newspaper Menu"))
        self.pushButton.setText(_translate("MainWindow", "Home Page"))
        self.pushButton_2.setText(_translate("MainWindow", "News"))
        self.pushButton_3.setText(_translate("MainWindow", "View"))
        self.pushButton_4.setText(_translate("MainWindow", "World"))
        self.pushButton_5.setText(_translate("MainWindow", "Video"))
        self.pushButton_6.setText(_translate("MainWindow", "Science"))
        self.pushButton_7.setText(_translate("MainWindow", "Business"))
        self.pushButton_8.setText(_translate("MainWindow", "Entertainment"))
        self.pushButton_9.setText(_translate("MainWindow", "Sport"))
        self.pushButton_10.setText(_translate("MainWindow", "Education"))
        self.pushButton_11.setText(_translate("MainWindow", "Setting"))
        self.pushButton_12.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Search news :"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">https://vov.vn/kinh-te/gia-xang-tang-cao-lam-xao-tron-doi-song-cua-nguoi-dan-post930605.vov</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
